# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60acda6ad8a819e5a490d7cdaf2c572a0cf65ebe679e797f1215baee5ecbcbdc34b43c5e9f1febe98dca0a68d9d7240ee8286430fb8db55377dbfd0e8047252

test:
  secret_key_base: dbdc33bdc1f6406e2fa814f18a139a796bf71131d9e79373441b8495b9cceebb33efa5a868aef7b6fd773985c112b2c36568b576183e11505f5595b806e2a7aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
